
name: Claim

on:
  push:
    branches: ["main"]

jobs:
  build:
    env:
      PY_COLORS: "1"
    name: Install Dependencies
    runs-on: ubuntu-latest
    container: ubuntu
    # strategy:
    #   max-parallel: 20
    #   fail-fast: false
    #   matrix:
    #     rangeIndex: ["2099 2104 1", "2099 2104 2", "2099 2104 3", "2099 2104 4", "2099 2104 5", "2099 2104 6", "2099 2104 7", "2104 2109 8", "2104 2109 9", "2104 2109 10", "2104 2109 11", "2104 2109 12", "2104 2109 13", "2104 2109 14", "2109 2114 15", "2109 2114 16", "2109 2114 17", "2109 2114 18", "2109 2114 19", "2109 2114 20", "2109 2114 21"]
    steps:
    - uses: actions/checkout@v4
    - name: Clone Warp
      run: |
        git clone https://github.com/cmj2002/warp-docker.git
    - name: Start containers
      env: 
        PROCESS_CLEAN: false
      run: |
        cd warp-docker
        docker compose up -d && curl -x socks5h://127.0.0.1:1080 https://cloudflare.com/cdn-cgi/trace
    - name: done
      run: exit
