
name: Claim

on:
  push:
    branches: ["main"]

jobs:
  build:
    env:
      PY_COLORS: "1"
    name: Install Dependencies
    runs-on: ubuntu-latest
    # strategy:
    #   max-parallel: 20
    #   fail-fast: false
    #   matrix:
    #     rangeIndex: ["2099 2104 1", "2099 2104 2", "2099 2104 3", "2099 2104 4", "2099 2104 5", "2099 2104 6", "2099 2104 7", "2104 2109 8", "2104 2109 9", "2104 2109 10", "2104 2109 11", "2104 2109 12", "2104 2109 13", "2104 2109 14", "2109 2114 15", "2109 2114 16", "2109 2114 17", "2109 2114 18", "2109 2114 19", "2109 2114 20", "2109 2114 21"]
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install WARP
      run: |
        echo "Setting up Cloudflare WARP..."
        sudo apt-get -y update
        curl -fsSL https://pkg.cloudflareclient.com/pubkey.gpg | sudo gpg --yes --dearmor --output /usr/share/keyrings/cloudflare-warp-archive-keyring.gpg
        echo "deb [arch=amd64 signed-by=/usr/share/keyrings/cloudflare-warp-archive-keyring.gpg] https://pkg.cloudflareclient.com/ $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/cloudflare-client.list
        sudo apt-get update && sudo apt-get install -y --no-install-recommends cloudflare-warp
        sudo warp-cli --accept-tos registration new
        sudo warp-cli --accept-tos mode warp+doh
        sudo warp-cli --accept-tos connect
        sleep 1
      shell: bash
    - name: Ensure connection is WARP'ed
      run: |
        echo "Checking WARP connection..."
        curl -s https://www.cloudflare.com/cdn-cgi/trace | grep "warp=on"
      shell: bash
    - name: done
      run: exit
